# Generated by Django 3.0.6 on 2020-07-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalBlogPost',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, null=True, upload_to='friendspic')),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
